# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-31 14:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_auto_20171231_1418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artworkimage',
            old_name='hidden',
            new_name='is_hidden',
        ),
        migrations.RenameField(
            model_name='artworkimage',
            old_name='thumbnail',
            new_name='is_thumbnail',
        ),
    ]
