# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-31 14:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0004_auto_20171231_1441'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artworkimage',
            old_name='is_hidden',
            new_name='visible',
        ),
    ]
