# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-31 14:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0005_auto_20171231_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artworkimage',
            name='is_thumbnail',
        ),
    ]
