# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-13 23:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0007_exhibition'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='exhibitions',
            field=models.ManyToManyField(to='work.Exhibition'),
        ),
    ]
