# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-13 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0008_artwork_exhibitions'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibition',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
