# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-13 23:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0009_exhibition_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='exhibitions',
        ),
        migrations.DeleteModel(
            name='Exhibition',
        ),
    ]
