# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-05 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitions', '0001_initial'),
        ('work', '0010_auto_20180313_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='exhibitions',
            field=models.ManyToManyField(to='exhibitions.Exhibition', verbose_name='list of exhibitions'),
        ),
    ]
