# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-07 00:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0012_auto_20180407_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='exhibitions',
            field=models.ManyToManyField(blank=True, to='exhibitions.Exhibition', verbose_name='list of exhibitions'),
        ),
    ]
