# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-07 00:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0013_auto_20180407_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artworkimage',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
