# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-07 00:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0014_auto_20180407_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
