# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-07 05:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0015_artwork_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artwork',
            options={'ordering': ['creation_date', 'title']},
        ),
        migrations.AlterField(
            model_name='artworkvideo',
            name='url',
            field=models.CharField(help_text='\n            Must be in the format https://www.youtube.com/embed/x-xxxxxxxxx\n        ', max_length=300),
        ),
    ]
