# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-07 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0018_auto_20180407_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='creation_date',
            field=models.DateField(help_text='You can just put 01/01/xxxx if you only know the year'),
        ),
    ]
