# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-07 23:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0020_auto_20180407_2354'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artwork',
            options={'ordering': ['date', 'title']},
        ),
        migrations.RenameField(
            model_name='artwork',
            old_name='creation_date',
            new_name='date',
        ),
    ]
