# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-08 00:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0021_auto_20180408_0018'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artwork',
            options={'ordering': ['-date', 'title']},
        ),
    ]
