# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-22 21:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0022_auto_20180408_0102'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtworkAudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=300)),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio', to='work.Artwork')),
            ],
        ),
    ]
