# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-22 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0026_auto_20180422_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='live',
            field=models.BooleanField(default=True, help_text='If this is unchecked then the artwork will not appear on artwork pages. Useful if you want to set a custom homepage artwork.', verbose_name='is live'),
        ),
    ]
