# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-22 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0028_auto_20180422_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artworkaudio',
            name='url',
            field=models.CharField(help_text='Must be in iframe format. You can find the code for this in the embed section of the share dialog in soundcloud.', max_length=500),
        ),
    ]
