# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-26 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0030_auto_20180424_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='date',
            field=models.DateField(help_text='You can just put 01/01/yyyy if you only know the year.', null=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='description',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artwork',
            name='live',
            field=models.BooleanField(default=True, help_text='If this is unchecked then the artwork will not appear anywhere on the site.', verbose_name='is live'),
        ),
    ]
