# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-07 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitions', '0002_exhibition_artworks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibition',
            name='artworks',
            field=models.ManyToManyField(to='work.Artwork', verbose_name='artworks from this exhibition'),
        ),
    ]
