# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-07 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitions', '0003_auto_20180407_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibition',
            name='artworks',
            field=models.ManyToManyField(help_text='\n            Artworks can also be added to exhibitions from the artwork edit\n            screen.\n        ', to='work.Artwork', verbose_name='exhibited artworks'),
        ),
    ]
