# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-07 22:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitions', '0004_auto_20180407_1053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exhibition',
            options={'ordering': ['date', 'title']},
        ),
    ]
