# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-08 00:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitions', '0005_auto_20180407_2336'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exhibition',
            options={'ordering': ['-date', 'title']},
        ),
    ]
