# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-26 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitions', '0006_auto_20180408_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibition',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exhibition',
            name='url',
            field=models.CharField(help_text='e.g. to the gallery webpage for this exhibition.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='artworks',
            field=models.ManyToManyField(help_text='Artworks can also be added to exhibitions from the artwork edit screen.', to='work.Artwork', verbose_name='exhibited artworks'),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
