# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-26 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitions', '0008_exhibition_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibition',
            name='artworks',
            field=models.ManyToManyField(blank=True, help_text='Artworks can also be added to exhibitions from the artwork edit screen.', to='work.Artwork', verbose_name='exhibited artworks'),
        ),
    ]
