# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-26 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitions', '0009_auto_20180426_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibition',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='url',
            field=models.CharField(blank=True, help_text='e.g. to the gallery webpage for this exhibition.', max_length=255, null=True),
        ),
    ]
