# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-26 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitions', '0012_auto_20180426_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibition',
            name='location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
