# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-26 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitions', '0013_auto_20180426_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibition',
            name='url',
            field=models.CharField(blank=True, default='', help_text='e.g. to the gallery webpage for this exhibition.', max_length=255),
        ),
    ]
