# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-26 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitions', '0014_auto_20180426_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibition',
            name='live',
            field=models.BooleanField(default=True, help_text='If this is unchecked then this exhibition will not appear anywhere on the site.', verbose_name='is live'),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='until'),
        ),
    ]
