# Generated by Django 2.0.4 on 2018-04-29 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitions', '0016_exhibitionimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibitionimage',
            name='exhibition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exhibition', to='exhibitions.Exhibition'),
        ),
    ]
