# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 10:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_artwork'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Artwork',
        ),
    ]
