# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_delete_artwork'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image_original', models.ImageField(upload_to='img/artwork')),
            ],
        ),
    ]
