# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 21:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_artwork'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='creation_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artwork',
            name='image_original',
            field=models.ImageField(upload_to=main.models.image_filename),
        ),
    ]
