# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-07 01:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20171220_2131'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shows',
        ),
    ]
