# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-07 01:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20180407_0250'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=100)),
                ('name', models.CharField(blank=True, choices=[('FB', 'Facebook'), ('SC', 'Soundcloud'), ('OT', 'Other')], default='OT', max_length=2, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='SocialMediaLinks',
        ),
    ]
