# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-07 01:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20180407_0252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialmedialink',
            old_name='name',
            new_name='type',
        ),
    ]
