# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-07 02:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20180407_0254'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('css_class', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='socialmedialink',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.SocialMediaType'),
        ),
    ]
