# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-07 10:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0018_auto_20180407_1154'),
        ('main', '0013_auto_20180407_0311'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('information', models.TextField()),
                ('contact_details', models.TextField()),
                ('homepage_artwork', models.OneToOneField(help_text='\n            Uses the first image for an artwork.\n        ', on_delete=django.db.models.deletion.CASCADE, to='work.Artwork', verbose_name='featured homepage artwork')),
            ],
        ),
    ]
