# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-07 11:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_siteconfig'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PageContent',
        ),
    ]
