# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-07 15:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_delete_pagecontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='contact_details',
            field=models.TextField(help_text='\n            The main text that appears on the contact page. html is allowed.\n        '),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='homepage_artwork',
            field=models.OneToOneField(help_text='\n            The large artwork that appears on the homepage.\n            Note that this uses the first image found (i.e. the one used in the\n            thumbnail).\n        ', on_delete=django.db.models.deletion.CASCADE, to='work.Artwork', verbose_name='featured homepage artwork'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='information',
            field=models.TextField(help_text='\n            The main text that appears on the info page. html is allowed.\n        '),
        ),
    ]
