# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-25 20:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20180422_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='homepage_artwork',
            field=models.OneToOneField(help_text='The large artwork that appears on the homepage.Note that this uses the first image found (i.e. the one used inthe thumbnail).', null=True, on_delete=django.db.models.deletion.CASCADE, to='work.Artwork', verbose_name='featured homepage artwork'),
        ),
    ]
