# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-25 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20180425_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='copyright_line',
            field=models.CharField(default='Copyright', max_length=255),
        ),
    ]
